# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [31]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [32]:
#Load csv and export dataframe
load_csv = "../WeatherPy/output_data/cities.csv"
citydf = pd.read_csv(load_csv)
del citydf['Unnamed: 0']
citydf.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Paita,-5.09,-81.11,67.10,83,100,13.71,PE,1607129815
1,Rincon,32.30,-81.24,64.11,93,90,9.17,US,1607129731
2,Yellowknife,62.46,-114.35,17.60,92,75,5.82,CA,1607129198
3,Hobart,-42.88,147.33,65.88,37,75,10.29,AU,1607129224
4,Tautira,-17.73,-149.15,86.00,58,75,10.29,PF,1607129815

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [33]:
#humidity heatmap

locations = citydf[["Lat", "Lng"]]
humidity = citydf['Humidity'].astype(int)
maxhumidity = humidity.max()


fig = gmaps.figure(center=(48.0, 0.0), zoom_level=2)

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=maxhumidity,
                                 point_radius = 2, opacity=1)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [34]:
#Narrow down cities to fit weather conditions
#A max temperature lower than 80 degrees but higher than 70.
lower80 = citydf.loc[citydf["Max Temp"]<80,:]
higher70 = lower80.loc[lower80["Max Temp"]>70,:]
higher70.head()
#Wind speed less than 10 mph.
wind = higher70.loc[higher70["Wind Speed"]<10,:]
#Zero cloudiness
zerocloud=wind.loc[wind["Cloudiness"]==0,:]
zerocloud=zerocloud.dropna(how='any').reset_index()
del zerocloud['index']
zerocloud

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Sidi,5.08,19.88,72.81,38,0,1.52,CF,1607129819
1,Saint-Philippe,-21.36,55.77,70.12,73,0,4.70,RE,1607129823
2,Mandiana,10.63,-8.68,72.64,30,0,1.59,GN,1607129837
3,Bonthe,7.53,-12.51,79.09,85,0,7.67,SL,1607129839
4,Sur,22.57,59.53,74.14,61,0,3.24,OM,1607129397
5,Yaan,7.38,8.57,77.09,61,0,6.49,NG,1607129842
6,Ambilobe,-13.20,49.05,74.08,84,0,2.19,MG,1607129847
7,Saint-Louis,16.33,-15.00,77.00,41,0,4.70,SN,1607129856
8,Gewanē,10.17,40.65,77.22,56,0,3.02,ET,1607129861
9,Oussouye,12.48,-16.55,74.32,94,0,4.70,SN,1607129805
10,Epe,6.58,3.98,77.65,91,0,4.18,NG,1607129863
11,Kouango,4.99,19.96,72.45,39,0,1.25,CF,1607129864
12,Una,20.82,71.03,71.83,45,0,5.14,IN,1607129868
13,Nioro,13.35,-15.75,73.00,54,0,8.48,GM,1607129310
14,Cayenne,4.93,-52.33,78.80,100,0,6.33,GF,1607129870
15,Arlit,18.74,7.39,78.62,20,0,6.91,NE,1607129872

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [42]:
hotels=[]
for i in range(len(zerocloud)):
    lat=zerocloud.loc[i]['Lat']
    lng=zerocloud.loc[i]['Lng']
    radius="5000"
    types="hotel"
    baseurl="https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="
    hotel_request=requests.get(f"{baseurl}{lat},{lng}&radius={radius}&type={types}&key={g_key}")
    hotel_request_json=hotel_request.json()
    try:
        hotels.append(hotel_request_json['results'][1]['name'])
    except:
        hotels.append("")

zerocloud['Hotel Name']=hotels
zerocloud

#https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=4.93,-52.33&radius=1500&type=hotel&key=g_key

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,Sidi,5.08,19.88,72.81,38,0,1.52,CF,1607129819,
1,Saint-Philippe,-21.36,55.77,70.12,73,0,4.70,RE,1607129823,"Chambres d'hôte ""La Trinité"""
2,Mandiana,10.63,-8.68,72.64,30,0,1.59,GN,1607129837,Ciel Petrole
3,Bonthe,7.53,-12.51,79.09,85,0,7.67,SL,1607129839,Bonthe Holiday Village
4,Sur,22.57,59.53,74.14,61,0,3.24,OM,1607129397,Sur Plaza Hotel
5,Yaan,7.38,8.57,77.09,61,0,6.49,NG,1607129842,Ishom Nursery And Primary School
6,Ambilobe,-13.20,49.05,74.08,84,0,2.19,MG,1607129847,Agence BNI Madagascar
7,Saint-Louis,16.33,-15.00,77.00,41,0,4.70,SN,1607129856,Belel Poste de Santé
8,Gewanē,10.17,40.65,77.22,56,0,3.02,ET,1607129861,Gewane Health Center
9,Oussouye,12.48,-16.55,74.32,94,0,4.70,SN,1607129805,Asamblea de Cooperacion por la Paz (Senegal)
10,Epe,6.58,3.98,77.65,91,0,4.18,NG,1607129863,Polaris Bank Limited
11,Kouango,4.99,19.96,72.45,39,0,1.25,CF,1607129864,"Kouango Centre de Santé ""A"""
12,Una,20.82,71.03,71.83,45,0,5.14,IN,1607129868,Noble Computers
13,Nioro,13.35,-15.75,73.00,54,0,8.48,GM,1607129310,Madina Mosque
14,Cayenne,4.93,-52.33,78.80,100,0,6.33,GF,1607129870,Hôtel Le Dronmi
15,Arlit,18.74,7.39,78.62,20,0,6.91,NE,1607129872,مكن لشراء الذهب. محمد جبرين

In [39]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in zerocloud.iterrows()]
locations = zerocloud[["Lat", "Lng"]]

In [40]:
# Add marker layer ontop of heat map
marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))